name: front

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test-frontend:
    name: Test Front-end
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd front
          npm install

      - name: Run tests with coverage
        run: |
          cd front
          npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless

  build-front:
    name: Build & Push Frontend Docker image
    runs-on: ubuntu-latest
    needs: [test-frontend]

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/front:latest
