name: SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  analyze-back:
    name: SonarCloud Analysis (back-end)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build backend (to generate .class files)
        run: |
          cd back
          mvn clean compile

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=jbchamp07_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
            -Dsonar.organization=jbchampkey
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=back/target/classes
  analyze-front:
    name: SonarCloud Analysis (front-end)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install front-end dependencies
        run: |
          cd front
          npm install

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=jbchamp07_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
            -Dsonar.organization=jbchampkey
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=front/src
            -Dsonar.inclusions=**/*.ts,**/*.js,**/*.jsx,**/*.tsx,**/*.vue,**/*.html,**/*.css
            -Dsonar.exclusions=**/node_modules/**
